name: Auto JsQndxx
on:
  schedule:
    - cron: '0 5 * * 1,3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        env:
          LARAVEL_SESSION: ${{ secrets.LARAVEL_SESSION }}
        run: |
          python main_actions.py
